spring:
  application:
    name: order-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/order-service

  datasource:
    url: jdbc:h2:mem:orders
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8081

product-service:
  base-url: http://localhost:8081

resilience4j:
  time-limiter:
    instances:
      productService:
        timeout-duration:
          seconds: 2
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 500ms
        ignore-exceptions:
          - lk.asanka.orders.exception.ProductNotFoundException

  circuit-breaker:
    instances:
      productService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3